### ISSUE TITLE
Country selector automatically selects random country

### ISSUE THREAD

**Issue by yaoyuanpa** [Netzfreiheit/STI-UI#103] opened 2016-04-02 08:19 UTC
Currently when you start the questionnaire, there is already a (random?) country selected; this could lead to a lot of users unintentionally sending their message with the wrong country selected. The country selection should show (--)
@filipesousa20 @ondrejpialek @musha68k

**Comment by yaoyuanpa** [comment] 2016-04-02 08:24
When the user forgets to choose one, it should say something like "Please choose a country before sending", with no option of finishing the sending process (same as: You haven't responded to any of the questions. Please edit the draft above or restart the questionnaire.)

**Comment by socialhack** [comment] 2016-04-03 06:04
@yaoyuanpa this is the intended behaviour for non-eu country IPs. From where are you accessing the tool?

**Comment by maltefiala** [comment] 2016-04-03 09:30
Not frontend related. Duplicate of https://github.com/EndzoneSoftware/STI/issues/8 . Please continue there.

**Closed by maltefiala** 2016-04-03 09:30 UTC
